config/routes.rb
Saturn::Application.routes.draw do

  resources :conferences, :only => [:index, :show]

  resources :physicians, :only => :index do
    collection do
      get "search"
    end
    member do
      get "schedule"
    end
    resource :physician_alias, :only => [:new, :create, :edit, :update]
  end

  resources :sections do
    resource :weekly_schedules
    match "/weekly_schedules/:date(.:format)" => "weekly_schedules#show",
      :date => /\d{4}-\d{2}-\d{2}/
    match "/weekly_schedules/:date/assignments(.:format)" => "assignments#index",
      :date => /\d{4}-\d{2}-\d{2}/
    resources :memberships, :only => :index do
      collection do
        get "manage"
        get "manage_new"
      end
    end
    resources :shift_tags, :only => [:index, :new, :create] do
      collection do
        get "search"
      end
    end
    resources :shifts, :except => [:show, :destroy]
    resources :call_shifts, :except => [:index, :show, :destroy]
    resources :vacation_shifts, :except => [:index, :show, :destroy]
    resources :meeting_shifts, :except => [:index, :show, :destroy]
    resource :rules, :only => [:show, :edit, :update]
    resources :assignment_requests, :except => [:show, :destroy] do
      member do
        post "approve"
      end
    end
    resource :admins, :only => [:show, :update]
    resource :reports, :only => :index do
      collection do
        get "search_shift_totals"
        post "shift_totals_report"
        scope "shifts/:shift_id/" do
          match "totals_by_day" => "reports#shift_totals_by_day"
        end
      end
    end
  end

  # provides an external API for consuming call schedules
  resources :section_call_schedules, :only => [:index]

  controller :schedules do
    match "/schedules/call(/:year/:month/:day)",
      :to => "schedules#weekly_call",
      :via => "get",
      :as => :weekly_call_schedule

    scope "/sections" do
      scope :path => "/:section_id/schedule(/:year/:month/:day)" do
        get "/" => "schedules#show_weekly_section",
          :as => :weekly_section_schedule
      end
    end
  end

  resources :rotations, :except => :show
  controller :residents do
    scope "/schedules/residents" do
      get "rotations", :as => :resident_rotations
    end
  end

  controller :reports do
    scope "/sections" do
      scope :path => "/:section_id/reports" do
        get "shift_totals", :as => :section_shift_totals
        scope "/people" do
          scope :path => "/:physician_id" do
            match "shift_totals", :to => "reports#section_physician_shift_totals",
              :via => "get", :as => :section_physician_shift_totals
          end
        end
      end
    end
  end

  match "admin", :to => "admin#index", :via => "get"
  scope "/admin" do
    resources :site_statistics, :only => :index
  end

  root :to => "schedules#weekly_call"
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  include SectionResourceController

  before_filter :authenticate_user!, :except => :index

  def index
    @members_by_group = @section.members_by_group
  end

  def manage_new
    authorize! :update, @section
    memberships = @section.memberships.map(&:physician_id)
    @physicians = Physician.all.select do |physician|
      !memberships.include?(physician.id)
    end
  end

  def manage
    authorize! :update, @section
    @members_by_group = @section.members_by_group
  end
end

app/views/memberships/index.haml
- page_title "#{@section.title} members"

- content_for :content_menu do
  = render "schedules/section_menu"

%ul
  != nav_item "Edit Members", manage_section_memberships_path(@section), { :class => "button" }, :update, @section

- @members_by_group.each do |group_name, people|
  %h3= group_name unless people.blank?
  %ul
    - people.each do |person|
      %li= person.full_name(:family_first)

app/views/memberships/index.html.haml
- page_title "#{@section.title} members"

%p
  %ul
    != nav_item "Add Members", manage_new_section_memberships_path(@section), { :class => "button" }, :update, @section
%p
  %ul
    != nav_item "Remove Members", manage_section_memberships_path(@section), { :class => "button" }, :update, @section

- @members_by_group.each do |group_name, people|
  %h3= group_name unless people.blank?
  %ul
    - people.each do |person|
      %li= person.full_name(:family_first)

app/views/memberships/manage.haml
- page_title "Manage #{@section.title} members"

- content_for :content_menu do
  = render "schedules/section_menu"

%p= link_to "Add Members", manage_new_section_memberships_path(@section)

- if @members_by_group
  %h3 Select members to remove
  = semantic_form_for @section do |section_form|
    = hidden_field_tag "redirect_path", section_memberships_path(@section)
    = section_form.buttons do
      = section_form.commit_button :button_html => { :class => "button" }
      %li
        or
        = link_to "Cancel", section_memberships_path(@section)
    - @members_by_group.each do |group_name, people|
      - if people.size > 0
        = section_form.inputs :name => group_name do
          - people.each do |person|
            = section_form.semantic_fields_for :memberships, person.section_memberships.where(:section_id => @section.id).first do |membership_form|
              = membership_form.input :_destroy, :as => :boolean, :label => person.full_name
    = section_form.buttons do
      = section_form.commit_button :button_html => { :class => "button" }
      %li
        or
        = link_to "Cancel", section_memberships_path(@section)

app/views/memberships/manage.html.haml
- page_title "Manage #{@section.title} members"

- if @members_by_group
  %h3 Select members to remove
  = semantic_form_for @section do |section_form|
    = hidden_field_tag "redirect_path", section_memberships_path(@section)
    = section_form.buttons do
      = section_form.commit_button :button_html => { :class => "button" }
      %li
        or
        = link_to "Cancel", section_memberships_path(@section)
    - @members_by_group.each do |group_name, people|
      - if people.size > 0
        = section_form.inputs :name => group_name do
          - people.each do |person|
            = section_form.semantic_fields_for :memberships, person.section_memberships.where(:section_id => @section.id).first do |membership_form|
              = membership_form.input :_destroy, :as => :boolean, :label => person.full_name
    = section_form.buttons do
      = section_form.commit_button :button_html => { :class => "button" }
      %li
        or
        = link_to "Cancel", section_memberships_path(@section)

app/views/memberships/manage_new.haml
- page_title "Manage #{@section.title} members"

- content_for :content_menu do
  = render "schedules/section_menu"

%h3 Add Members

%div.form-container
  = semantic_form_for @section do |section_form|
    = hidden_field_tag "redirect_path", section_memberships_path(@section)
    = section_form.buttons do
      = section_form.commit_button
      %li
        or
        = link_to "Cancel", section_memberships_path(@section)
    %ul
      - @physicians.each do |physician|
        %li
          = check_box_tag "section[memberships_attributes][][physician_id]", physician.id
          = label_tag :physician_id, physician.full_name
    = section_form.buttons do
      = section_form.commit_button
      %li
        or
        = link_to "Cancel", section_memberships_path(@section)

app/views/memberships/manage_new.html.haml
- page_title "Manage #{@section.title} members"

%h3 Add Members

%div.form-container
  = semantic_form_for @section do |section_form|
    = hidden_field_tag "redirect_path", section_memberships_path(@section)
    = section_form.buttons do
      = section_form.commit_button :button_html => { :class => "button" }
      %li
        or
        = link_to "Cancel", section_memberships_path(@section)
    %ul
      - @physicians.each do |physician|
        %li
          = check_box_tag "section[memberships_attributes][][physician_id]", physician.id
          = label_tag :section_memberships_attributes__physician_id, physician.full_name
    = section_form.buttons do
      = section_form.commit_button :button_html => { :class => "button" }
      %li
        or
        = link_to "Cancel", section_memberships_path(@section)

app/views/memberships/new.haml
- content_for :content_menu do
  = render "schedules/section_menu"

%h3 Add Members

%div.form-container
  = semantic_form_for @section do |section_form|
    = hidden_field_tag "redirect_path", section_memberships_path(@section)
    = section_form.buttons do
      = section_form.commit_button
      %li
        or
        = link_to "Cancel", section_memberships_path(@section)
    %ul
      - @physicians.each do |physician|
        %li
          = check_box_tag "section[memberships_attributes][][physician_id]", physician.id
          = label_tag :physician_id, physician.full_name
    = section_form.buttons do
      = section_form.commit_button
      %li
        or
        = link_to "Cancel", section_memberships_path(@section)