config/routes.rb
Saturn::Application.routes.draw do

  resources :conferences, :only => [:index, :show]

  resources :physicians, :only => :index do
    collection do
      get "search"
    end
    member do
      get "schedule"
    end
    resource :physician_alias, :only => [:new, :create, :edit, :update]
  end

  resources :sections do
    resource :weekly_schedules
    match "/weekly_schedules/:date(.:format)" => "weekly_schedules#show",
      :date => /\d{4}-\d{2}-\d{2}/
    match "/weekly_schedules/:date/assignments(.:format)" => "assignments#index",
      :date => /\d{4}-\d{2}-\d{2}/
    resources :memberships, :only => :index do
      collection do
        get "manage"
        get "manage_new"
      end
    end
    resources :shift_tags, :only => [:index, :new, :create] do
      collection do
        get "search"
      end
    end
    resources :shifts, :except => [:show, :destroy]
    resources :call_shifts, :except => [:index, :show, :destroy]
    resources :vacation_shifts, :except => [:index, :show, :destroy]
    resources :meeting_shifts, :except => [:index, :show, :destroy]
    resource :rules, :only => [:show, :edit, :update]
    resources :assignment_requests, :except => [:show, :destroy] do
      member do
        post "approve"
      end
    end
    resource :admins, :only => [:show, :update]
    resource :reports, :only => :index do
      collection do
        get "search_shift_totals"
        post "shift_totals_report"
        scope "shifts/:shift_id/" do
          match "totals_by_day" => "reports#shift_totals_by_day"
        end
      end
    end
  end

  # provides an external API for consuming call schedules
  resources :section_call_schedules, :only => [:index]

  controller :schedules do
    match "/schedules/call(/:year/:month/:day)",
      :to => "schedules#weekly_call",
      :via => "get",
      :as => :weekly_call_schedule

    scope "/sections" do
      scope :path => "/:section_id/schedule(/:year/:month/:day)" do
        get "/" => "schedules#show_weekly_section",
          :as => :weekly_section_schedule
      end
    end
  end

  resources :rotations, :except => :show
  controller :residents do
    scope "/schedules/residents" do
      get "rotations", :as => :resident_rotations
    end
  end

  controller :reports do
    scope "/sections" do
      scope :path => "/:section_id/reports" do
        get "shift_totals", :as => :section_shift_totals
        scope "/people" do
          scope :path => "/:physician_id" do
            match "shift_totals", :to => "reports#section_physician_shift_totals",
              :via => "get", :as => :section_physician_shift_totals
          end
        end
      end
    end
  end

  match "admin", :to => "admin#index", :via => "get"
  scope "/admin" do
    resources :site_statistics, :only => :index
  end

  root :to => "schedules#weekly_call"
end

app/models/rotation.rb
class Rotation < ActiveRecord::Base

  attr_accessible :title, :description

  validates :title, :presence => true

  before_validation { clean_text_attributes :title, :description }

end

app/controllers/rotations_controller.rb
class RotationsController < ApplicationController

  before_filter :authenticate_user!
  before_filter { authorize! :manage, Rotation }

  def index
    @rotations = Rotation.all
  end

  def new
    @rotation = Rotation.new
  end

  def create
    @rotation = Rotation.new(params[:rotation])

    if @rotation.save
      flash[:notice] = "Successfully created rotation"
      return(redirect_to rotations_path)
    end
    flash.now[:error] = "Unable to create rotation: #{@rotation.errors.full_messages.join(", ")}"
    render :new
  end

  def edit
    @rotation = Rotation.find(params[:id])

  rescue ActiveRecord::RecordNotFound
    flash[:error] = "Error: requested rotation not found"
    redirect_to rotations_path
  end

  def update
    @rotation = Rotation.find(params[:id])

    if @rotation.update_attributes(params[:rotation])
      flash[:notice] = "Successfully updated rotation"
      return(redirect_to rotations_path)
    end
    flash.now[:error] = "Unable to update rotation: #{@rotation.errors.full_messages.join(", ")}"
    render :edit

  rescue ActiveRecord::RecordNotFound
    flash[:error] = "Error: requested rotation not found"
    redirect_to rotations_path
  end

  def destroy
    @rotation = Rotation.find(params[:id])

    if @rotation.destroy
      flash[:notice] = "Successfully deleted rotation"
    else
      flash[:error] = "Error: failed to delete rotation"
    end
    return(redirect_to rotations_path)

  rescue ActiveRecord::RecordNotFound
    flash[:error] = "Error: requested rotation not found"
    redirect_to rotations_path
  end
end

app/views/rotations/_form.html.haml
- content_for :content_menu do
  = render "rotation_menu.html"

%div.form-container
  = semantic_form_for rotation do |rotation_form|
    = rotation_form.inputs :title, :description
    = rotation_form.buttons do
      = rotation_form.commit_button
      %li
        or
        = link_to "Cancel", rotations_path

app/views/rotations/_rotation_menu.haml
%h2 Residents

%div.navcontainer
  %ul.navlist
    != nav_item "Rotation Schedule", resident_rotations_path
    != nav_item "Edit Rotations", rotations_path, {}, :manage, Rotation

app/views/rotations/_rotation_menu.html.haml
%h2 Residents

%div.navcontainer
  %ul.navlist
    != nav_item "Rotation Schedule", resident_rotations_path
    != nav_item "Edit Rotations", rotations_path, {}, :manage, Rotation

app/views/rotations/edit.html.haml
= render "form", :rotation => @rotation

app/views/rotations/index.html.haml
- content_for :content_menu do
  = render "rotation_menu.html"

%h3 Rotations

%p= link_to "Add Rotation", new_rotation_path

%table
  - @rotations.each do |rotation|
    %tr
      %td= link_to rotation.title, edit_rotation_path(rotation), :title => "Edit"
      %td= rotation.description

app/views/rotations/new.html.haml
= render "form", :rotation => @rotation