config/routes.rb
Saturn::Application.routes.draw do

  resources :conferences, :only => [:index, :show]

  resources :physicians, :only => :index do
    collection do
      get "search"
    end
    member do
      get "schedule"
    end
    resource :physician_alias, :only => [:new, :create, :edit, :update]
  end

  resources :sections do
    resource :weekly_schedules
    match "/weekly_schedules/:date(.:format)" => "weekly_schedules#show",
      :date => /\d{4}-\d{2}-\d{2}/
    match "/weekly_schedules/:date/assignments(.:format)" => "assignments#index",
      :date => /\d{4}-\d{2}-\d{2}/
    resources :memberships, :only => :index do
      collection do
        get "manage"
        get "manage_new"
      end
    end
    resources :shift_tags, :only => [:index, :new, :create] do
      collection do
        get "search"
      end
    end
    resources :shifts, :except => [:show, :destroy]
    resources :call_shifts, :except => [:index, :show, :destroy]
    resources :vacation_shifts, :except => [:index, :show, :destroy]
    resources :meeting_shifts, :except => [:index, :show, :destroy]
    resource :rules, :only => [:show, :edit, :update]
    resources :assignment_requests, :except => [:show, :destroy] do
      member do
        post "approve"
      end
    end
    resource :admins, :only => [:show, :update]
    resource :reports, :only => :index do
      collection do
        get "search_shift_totals"
        post "shift_totals_report"
        scope "shifts/:shift_id/" do
          match "totals_by_day" => "reports#shift_totals_by_day"
        end
      end
    end
  end

  # provides an external API for consuming call schedules
  resources :section_call_schedules, :only => [:index]

  controller :schedules do
    match "/schedules/call(/:year/:month/:day)",
      :to => "schedules#weekly_call",
      :via => "get",
      :as => :weekly_call_schedule

    scope "/sections" do
      scope :path => "/:section_id/schedule(/:year/:month/:day)" do
        get "/" => "schedules#show_weekly_section",
          :as => :weekly_section_schedule
      end
    end
  end

  resources :rotations, :except => :show
  controller :residents do
    scope "/schedules/residents" do
      get "rotations", :as => :resident_rotations
    end
  end

  controller :reports do
    scope "/sections" do
      scope :path => "/:section_id/reports" do
        get "shift_totals", :as => :section_shift_totals
        scope "/people" do
          scope :path => "/:physician_id" do
            match "shift_totals", :to => "reports#section_physician_shift_totals",
              :via => "get", :as => :section_physician_shift_totals
          end
        end
      end
    end
  end

  match "admin", :to => "admin#index", :via => "get"
  scope "/admin" do
    resources :site_statistics, :only => :index
  end

  root :to => "schedules#weekly_call"
end

app/controllers/schedules_controller.rb
require 'saturn/dates'

class SchedulesController < ApplicationController

  include Saturn::Dates

  def weekly_call
    dates = week_dates_beginning_with(week_start_date)
    @schedule_presenter = ::Logical::CallSchedulePresenter.new(:dates => dates)
  end

  def show_weekly_section
    date_params = params[:date] || params
    request_date = date_params[:year].nil? ? nil : "#{date_params[:year]}-#{date_params[:month]}-#{date_params[:day]}"
    start_date = monday_of_week_with(request_date)
    dates = week_dates_beginning_with(start_date)
    @section = Section.find(params[:section_id])
    schedule = @section.weekly_schedules.published.find_by_date(start_date) ||
      @section.weekly_schedules.build(:date => start_date)
    @assignments = schedule.is_published ? schedule.assignments : []
    physician_names_by_id = @section.members.each_with_object({}) do |physician, hsh|
      hsh[physician.id] = physician.short_name
    end
    @view_mode = params[:view_mode]
    presenter_options = case @view_mode.to_i
      when 0, 1
        { :col_type => :dates, :row_type => :shifts }
      when 2
        { :col_type => :dates, :row_type => :physicians }
      end
    @schedule_presenter = ::Logical::WeeklySchedulePresenter.new(
      :section => @section,
      :dates => dates,
      :assignments => @assignments,
      :weekly_schedule => schedule,
      :physician_names_by_id => physician_names_by_id,
      :options => presenter_options
    )

    respond_to do |format|
      format.html { render :layout => "section" }
      format.xls { render :xls => @schedule_presenter, :template => "schedules/weekly_section_schedule.xls", :layout => false }
    end
  end

  private

  # calculate the date at the beginning of the week based on the params
  def week_start_date
    date_params = params[:date] || params
    request_date = date_params[:year].nil? ? nil : "#{date_params[:year]}-#{date_params[:month]}-#{date_params[:day]}"
    start_date = monday_of_week_with(request_date)
  end
end

app/views/schedules/_assignment.haml
- assignment ||= Assignment.new
- assignment_id = assignment.id
- assignment_duration = assignment.duration
- physician_id = assignment.physician_id
- public_note = assignment.public_note
- private_note = assignment.private_note
- position = assignment.position
- people_names ||= {}
- shift_id ||= nil
- date ||= nil
%div.assignment{ :id => "assignment_#{assignment_id}" }><
  %span.person_name><= people_names[physician_id]
  %span.button><
    %span.ui-state-default><
      - duration_class = assignment_duration.nil? ? "" : "ui-icon ui-icon-clock"
      %span.duration_icon{ :class => duration_class }>< &nbsp;
    - notes_class = public_note.blank? ? "" : "public"
    - notes_class += private_note.blank? ? "" : "private"
    %span.notes_icon{ :class => notes_class }>< &nbsp;
  = hidden_field_tag "assignments[][id]", assignment_id
  = hidden_field_tag "assignments[][shift_id]", shift_id
  = hidden_field_tag "assignments[][physician_id]", physician_id
  = hidden_field_tag "assignments[][date]", date
  = hidden_field_tag "assignments[][position]", position
  = hidden_field_tag "assignments[][_destroy]", false
  %div.details><
    %p><= link_to "Delete", "#", :class => "destructive"
    = label_tag "Public note"
    = text_area_tag "assignments[][public_note]", public_note
    = label_tag "Private note"
    = text_area_tag "assignments[][private_note]", private_note
    = label_tag "Modified duration"
    - durations = ["Select...", 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
    = select_tag "assignments[][duration]", options_for_select(durations, assignment_duration)

app/views/schedules/_date_header.haml
%th.date><
  %span.date_value= date_header
  %span.date_string= short_date(date_header)

app/views/schedules/_date_header.html.haml
%th{ :class => date == Date.today ? "current-date" : "date" }
  %div.date-label= holiday_title_on(date)
  %span= date.to_s(:short_with_weekday)

app/views/schedules/_person.haml
%div.person{ :id => "person_#{person.id}" }><
  %span.name= person.short_name

app/views/schedules/_rule_conflict_summary.html.haml
%li= "#{physician_names_by_id[summary[:physician_id]]} (#{summary[:description]})"

app/views/schedules/_rules_conflicts.haml
- unless @assignments.blank?
  - duration_rule = @section.weekly_shift_duration_rule
  - count_rules = @section.daily_shift_count_rules
  - unless duration_rule.blank? && count_rules.blank?
    %h3 Rules Conflicts
    - assignments_by_physician_id = @assignments.group_by(&:physician_id)
    - if duration_rule
      - offenders = duration_rule.process(assignments_by_physician_id)
      - if duration_rule.minimum
        %h4= "Below weekly minimum (#{duration_rule.minimum})"
        %ul
          - offenders[:below_minimum].each do |summary|
            %li= "#{@physician_names_by_id[summary[:physician_id]]} (#{summary[:description]})"
      - if duration_rule.maximum
        %h4= "Above weekly maximum (#{duration_rule.maximum})"
        %ul
          - offenders[:above_maximum].each do |summary|
            %li= "#{@physician_names_by_id[summary[:physician_id]]} (#{summary[:description]})"

    - count_rules.each do |count_rule|
      - if count_rule.maximum
        - over = count_rule.process(assignments_by_physician_id)
        %h4= "Above daily maximum for #{count_rule.shift_tag.title}"
        %ul
          - over.each do |summary|
            %li= "#{@physician_names_by_id[summary[:physician_id]]} (#{summary[:description]})"

app/views/schedules/_rules_conflicts.html.haml
- unless assignments.blank?
  - conflicts_summaries = schedule.rules_conflicts
  - duration_rule = conflicts_summaries.duration_rule
  - count_rules = conflicts_summaries.count_rules
  - unless duration_rule.blank? && count_rules.blank?
    %h3 Rules Conflicts
    - if duration_rule
      - conflicts = conflicts_summaries.weekly_conflicts
      - if duration_rule.minimum
        %h4= duration_rule.minimum_summary
        %ul
          = render :partial => "rule_conflict_summary", :collection => conflicts[:below_minimum], :as => :summary, :locals => { :physician_names_by_id => physician_names_by_id }
      - if duration_rule.maximum
        %h4= duration_rule.maximum_summary
        %ul
          = render :partial => "rule_conflict_summary", :collection => conflicts[:above_maximum], :as => :summary, :locals => { :physician_names_by_id => physician_names_by_id }

    - count_rules.each do |count_rule|
      - if count_rule.maximum
        %h4= count_rule.summary
        %ul
          = render :partial => "rule_conflict_summary", :collection => conflicts_summaries.physician_ids_over_daily_count_max(count_rule), :as => :summary, :locals => { :physician_names_by_id => physician_names_by_id }

app/views/schedules/_schedule_cell.html.haml
%td><
  - if schedule_cell.present?
    - schedule_cell.each do |summary|
      %span{ :class => summary[:status] }= summary[:text]
      - if summary[:note].present?
        %span.note
          = image_tag "pub-note.gif", :alt => summary[:note]
          %span.note-text= summary[:note]
      - if summary[:duration].present?
        %span.note.ui-state-default{ :style => "border:none;" }
          %span.ui-icon.ui-icon-clock
          %span.note-text= summary[:duration]
      %br
  - else
    &nbsp;

app/views/schedules/_section_menu.haml
- if @section && !@section.new_record?
  %h2= @section.title
  %div.navcontainer
    %ul.navlist
      - date = @dates ? @dates.first : Date.today
      != nav_item "View Schedule", weekly_section_schedule_path(@section, :year => date.year, :month => date.month, :day => date.day), {}, nil, nil, /sections\/[\w-]+\/schedule/
      != nav_item "Vacation Requests", section_vacation_requests_path(@section), {}, nil, nil, /sections\/[\w-]+\/vacation_requests/
      != nav_item "Meeting Requests", section_meeting_requests_path(@section), {}, nil, nil, /sections\/[\w-]+\/meeting_requests/
      != nav_item "Edit Schedule", edit_section_weekly_schedules_path(@section, :anchor => date), {}, :update, @section, /sections\/[\w-]+\/weekly_schedules\/edit/
      != nav_item "Rules", section_rules_path(@section), {}, nil, nil, /sections\/[\w-]+\/rules/
      != nav_item "Members", section_memberships_path(@section), {}, nil, nil, /sections\/[\w-]+\/members/
      != nav_item "Shifts", section_shifts_path(@section), {}, :update, @section, /sections\/[\w-]+\/shifts/
      != nav_item "Shift Categories", section_shift_tags_path(@section), {}, :update, @section, /sections\/[\w-]+\/shift_tags/
      != nav_item "Reports", section_shift_totals_path(@section), {}, nil, nil, /sections\/[\w-]+\/reports/
      != nav_item "Administrators", section_admins_path(@section), {}, :manage, @section, /sections\/[\w-]+\/admins/

app/views/schedules/_section_menu.html.haml
- if @section && !@section.new_record?
  %h2= @section.title
  %div.navcontainer
    %ul.navlist
      - date = @dates ? @dates.first : Date.today
      != nav_item "View Schedule", weekly_section_schedule_path(@section, :year => date.year, :month => date.month, :day => date.day), {}, nil, nil, /sections\/[\w-]+\/schedule/
      != nav_item "Requests", section_assignment_requests_path(@section), {}, nil, nil, /sections\/[\w-]+\/assignment_requests/
      != nav_item "Edit Schedule", edit_section_weekly_schedules_path(@section, :anchor => date), {}, :update, @section, /sections\/[\w-]+\/weekly_schedules\/edit/
      != nav_item "Rules", section_rules_path(@section), {}, nil, nil, /sections\/[\w-]+\/rules/
      != nav_item "Members", section_memberships_path(@section), {}, nil, nil, /sections\/[\w-]+\/members/
      != nav_item "Shifts", section_shifts_path(@section), {}, :update, @section, /sections\/[\w-]+\/shifts/
      != nav_item "Shift Categories", section_shift_tags_path(@section), {}, :update, @section, /sections\/[\w-]+\/shift_tags/
      != nav_item "Reports", section_shift_totals_path(@section), {}, nil, nil, /sections\/[\w-]+\/reports/
      != nav_item "Administrators", section_admins_path(@section), {}, :manage, @section, /sections\/[\w-]+\/admins/

app/views/schedules/_shift_header.haml
%th.shift_label{ :id => shift_header.id }><= shift_header.label

app/views/schedules/show_weekly_section.html.haml
- page_title "#{@section.title} weekly schedule"

- content_for :stylesheets do
  = stylesheet_link_tag 'schedule'

- week_start_date = @schedule_presenter.dates.first
%h3= render "shared/date_select_widget", :prefix => "Published schedule for", :current_date => week_start_date, :view_path => weekly_section_schedule_path(@section, :year => week_start_date.year, :month => week_start_date.month, :day => week_start_date.day)
%p= link_to "View today", weekly_section_schedule_path(@section)

%p.content_actions= link_to "Download as Excel", weekly_section_schedule_path(@section, :format => :xls, :date => { :year => week_start_date.year, :month => week_start_date.month, :day => week_start_date.day }, :view_mode => @view_mode)

%table.schedule.wide-schedule
  %thead
    %tr
      %th.empty
        - if @view_mode == "2"
          = link_to "View by Shifts", weekly_section_schedule_path(@section, :year => week_start_date.year, :month => week_start_date.month, :day => week_start_date.day)
        - else
          = link_to "View by Physician", weekly_section_schedule_path(@section, :year => week_start_date.year, :month => week_start_date.month, :day => week_start_date.day, :view_mode => 2)
      - @schedule_presenter.each_col_header do |col_header|
        = render :partial => "schedules/headers/html/#{col_header[:type]}.html", :object => col_header[:object]
%div.schedule-wrapper
  %table.schedule.wide-schedule
    %tbody
      - @schedule_presenter.rows.each do |row|
        %tr{ :class => cycle("odd", "") }
          %th><= render :partial => "schedules/headers/html/#{row.header[:type]}.html", :object => row.header[:object]
          = render :partial => "schedule_cell.html", :collection => row.cells

%div#rules-conflicts= render "rules_conflicts.html", :physician_names_by_id => @schedule_presenter.physician_names_by_id, :schedule => @schedule_presenter.weekly_schedule, :assignments => @assignments

app/views/schedules/weekly_call.haml
- page_title "On Call"

%h3 Published Call Schedule
%h3= "Week of #{@dates.first.to_s(:long)}"
= form_tag weekly_call_schedule_path, :method => :get do
  = select_year(@dates.first)
  = select_month(@dates.first)
  = select_day(@dates.first)
  = submit_tag "Jump to date"
%p= link_to "view today", weekly_call_schedule_path

- mapped_assignments = @call_assignments.group_by {|a| [a.shift_id, a.date]}
- shifts_by_section = @call_shifts.group_by {|s| s.section}
%table.schedule
  %thead
    %tr
      %th
      - @dates.each do |date|
        %th{ :class => date == Date.today ? "current-date" : "" }= short_date(date)
  %tbody
    - shifts_by_section.each do |section, shifts|
      %tr
        %th{ :colspan => 8, :style => "background-color: #c0d9d9;" }= section.title
      - shifts.each do |shift|
        %tr
          %th= shift.title
          - @dates.each do |date|
            - assignments_by_shift_and_date = mapped_assignments[[shift.id, date]]
            - if assignments_by_shift_and_date
              %td{ :class => date.today? ? "current-date" : "" }
                - assignments_by_shift_and_date.each do |assignment|
                  - physician = @physicians_by_id[assignment.physician_id]
                  = link_to physician.short_name, schedule_physician_path(physician)
                  %br
            - else
              %td &nbsp;

app/views/schedules/weekly_call.html.haml
- page_title "On Call"

- content_for :stylesheets do
  = stylesheet_link_tag "schedule"

- content_for :javascripts do
  = javascript_include_tag 'shared/date_selector'

- week_start_date = @schedule_presenter.dates.first
%h3= render "shared/date_select_widget", :prefix => "Published call schedule for", :current_date => week_start_date, :view_path => weekly_call_schedule_path(:year => week_start_date.year, :month => week_start_date.month, :day => week_start_date.day)

%div.schedule-column-header.prepended-column-header
  %div.placeholder &nbsp;
  %div.placeholder &nbsp;
  - last_week = week_start_date - 7
  %a{ :href => weekly_call_schedule_path(:date => { :year => last_week.year, :month => last_week.month, :day => last_week.day }) }
    &laquo; previous week

%table.schedule
  %thead
    %tr
      %th.empty
      = render :partial => "date_header", :collection => @schedule_presenter.dates, :as => :date
  %tbody
    - @schedule_presenter.shifts_by_section.each do |section, shifts|
      %tr
        %th.section-week{ :colspan => 8 }= section.title
      - shifts.each do |shift|
        %tr
          %th= shift.title
          - @schedule_presenter.dates.each do |date|
            = render :partial => "schedule_cell.html", :object => @schedule_presenter.summaries_by_section_id_shift_id_and_date(section.id, shift.id, date)

%div.schedule-column-header.appended-column-header
  %div.placeholder &nbsp;
  %div.placeholder &nbsp;
  - next_week = week_start_date + 7
  %a{ :href => weekly_call_schedule_path(:date => { :year => next_week.year, :month => next_week.month, :day => next_week.day }) }
    next week &raquo;