config/routes.rb
Saturn::Application.routes.draw do

  resources :conferences, :only => [:index, :show]

  resources :physicians, :only => :index do
    collection do
      get "search"
    end
    member do
      get "schedule"
    end
    resource :physician_alias, :only => [:new, :create, :edit, :update]
  end

  resources :sections do
    resource :weekly_schedules
    match "/weekly_schedules/:date(.:format)" => "weekly_schedules#show",
      :date => /\d{4}-\d{2}-\d{2}/
    match "/weekly_schedules/:date/assignments(.:format)" => "assignments#index",
      :date => /\d{4}-\d{2}-\d{2}/
    resources :memberships, :only => :index do
      collection do
        get "manage"
        get "manage_new"
      end
    end
    resources :shift_tags, :only => [:index, :new, :create] do
      collection do
        get "search"
      end
    end
    resources :shifts, :except => [:show, :destroy]
    resources :call_shifts, :except => [:index, :show, :destroy]
    resources :vacation_shifts, :except => [:index, :show, :destroy]
    resources :meeting_shifts, :except => [:index, :show, :destroy]
    resource :rules, :only => [:show, :edit, :update]
    resources :assignment_requests, :except => [:show, :destroy] do
      member do
        post "approve"
      end
    end
    resource :admins, :only => [:show, :update]
    resource :reports, :only => :index do
      collection do
        get "search_shift_totals"
        post "shift_totals_report"
        scope "shifts/:shift_id/" do
          match "totals_by_day" => "reports#shift_totals_by_day"
        end
      end
    end
  end

  # provides an external API for consuming call schedules
  resources :section_call_schedules, :only => [:index]

  controller :schedules do
    match "/schedules/call(/:year/:month/:day)",
      :to => "schedules#weekly_call",
      :via => "get",
      :as => :weekly_call_schedule

    scope "/sections" do
      scope :path => "/:section_id/schedule(/:year/:month/:day)" do
        get "/" => "schedules#show_weekly_section",
          :as => :weekly_section_schedule
      end
    end
  end

  resources :rotations, :except => :show
  controller :residents do
    scope "/schedules/residents" do
      get "rotations", :as => :resident_rotations
    end
  end

  controller :reports do
    scope "/sections" do
      scope :path => "/:section_id/reports" do
        get "shift_totals", :as => :section_shift_totals
        scope "/people" do
          scope :path => "/:physician_id" do
            match "shift_totals", :to => "reports#section_physician_shift_totals",
              :via => "get", :as => :section_physician_shift_totals
          end
        end
      end
    end
  end

  match "admin", :to => "admin#index", :via => "get"
  scope "/admin" do
    resources :site_statistics, :only => :index
  end

  root :to => "schedules#weekly_call"
end

app/models/section.rb
class Section < ActiveRecord::Base

  attr_accessible :title, :memberships_attributes, :shifts_attributes,
    :shift_tags_attributes, :administrator_ids, :section_shifts_attributes,
    :weekly_shift_duration_rule_attributes, :daily_shift_count_rules_attributes

  SCHEDULE_GROUPS = %w[Faculty Fellows Residents]

  has_friendly_id :title, :use_slug => true

  with_options :dependent => :destroy do |assoc|
    assoc.has_many :shift_tags
    assoc.has_many :memberships,:class_name => 'SectionMembership'
    assoc.has_many :weekly_schedules
    assoc.has_many :section_shifts
    assoc.has_one :weekly_shift_duration_rule
    assoc.has_many :daily_shift_count_rules
    assoc.has_one :section_role_assignment
  end
  has_many :shifts, :through => :section_shifts
  has_many :call_shifts, :through => :section_shifts
  has_many :vacation_shifts, :through => :section_shifts
  has_many :meeting_shifts, :through => :section_shifts
  has_many :shift_tag_assignments, :through => :section_shifts
  has_one :admin_role, :through => :section_role_assignment, :source => :role
  accepts_nested_attributes_for :shift_tags, :allow_destroy => true
  accepts_nested_attributes_for :memberships, :allow_destroy => true
  accepts_nested_attributes_for :shifts
  accepts_nested_attributes_for :call_shifts
  accepts_nested_attributes_for :vacation_shifts
  accepts_nested_attributes_for :meeting_shifts
  accepts_nested_attributes_for :section_shifts
  accepts_nested_attributes_for :weekly_shift_duration_rule
  accepts_nested_attributes_for :daily_shift_count_rules

  validates :title, :presence => true, :uniqueness => true

  before_validation { clean_text_attributes :title }

  def as_json(options = {})
    {
      :id => id,
      :title => title,
      :members => members.includes(:names_alias),
      :shifts => active_shifts
    }
  end

  def to_s
    title
  end

  def assignments
    Assignment.includes(:shift).where(:shift_id => shifts.map(&:id))
  end

  def assignment_requests
    AssignmentRequest.includes(:shift).where(:shift_id => shifts.map(&:id))
  end

  def active_shifts(options = nil)
    date = options.nil? ? Date.today : options[:as_of]
    Shift.joins(:section_shifts).merge(section_shifts.active_as_of(date))
  end

  def retired_shifts_as_of(date)
    Shift.joins(:section_shifts).merge(section_shifts.retired_as_of(date))
  end

  def tags_for_shift(shift)
    @shift_tag_by_id ||= shift_tags.scoped.hash_by_id
    @shift_tags_by_shift_id ||= shift_tag_assignments.
      includes(:section_shift, :shift_tag).
      each_with_object({}) do |assignment, hsh|
        hsh[assignment.section_shift.shift_id] ||= []
        hsh[assignment.section_shift.shift_id] << assignment.shift_tag
      end
    @shift_tags_by_shift_id[shift.id] || []
  end

  # Finds all published schedules that intersect with the +dates+ parameter,
  # then returns all assignments for those schedules.
  def published_assignments_by_dates(dates)
    published_schedules = weekly_schedules.published.include_dates dates
    published_dates = published_schedules.map(&:dates).flatten
    assignments.where(:date => published_dates)
  end

  def members
    Physician.by_ids member_ids
  end

  def member_ids
    memberships.map(&:physician_id)
  end

  # returns the members of this section grouped by SCHEDULE_GROUPS, i.e.:
  # { "Faculty" => [p1, p2], "Fellows" => [p3, p4], "Residents" => [p5, p6] }
  def members_by_group
    SCHEDULE_GROUPS.each_with_object({}) do |group, grouped_members|
      grouped_members[group] = members.select do |physician|
        physician.in_group? group
      end
    end
  end

  def members_by_group_json
    [
      "\"groups\":[",
        members_by_group.map do |group_title, physicians|
          [
          "{",
            "\"title\":\"#{group_title}\",",
            "\"physicians\":[",
              physicians.map do |physician|
                physician.to_json
              end.join(","),
            "]",
          "}"
          ].join("")
        end.join(","),
      "]"
    ].join("")
  end

  def members_json
    [
      "\"physicians\":[",
        members.includes(:names_alias).map do |physician|
          physician.to_json
        end.join(","),
      "]"
    ].join("")
  end

  def create_admin_role
    return admin_role unless admin_role.blank?
    manage_section_permission = Deadbolt::Permission.
      find_or_create_by_action_and_target_type("manage", "Section")
    role_name = "#{title} Administrator"
    unless manage_section_permission.roles.exists? :name => role_name
      manage_section_permission.roles.create :name => role_name
    end
    role = manage_section_permission.roles.find_by_name(role_name)
    role.role_permissions.first.update_attributes(:target_id => id)
    create_section_role_assignment(:role => role)
    role
  end

  def administrators
    return [] if admin_role.blank?
    admin_role.users
  end

  def administrator_emails
    administrators.map(&:email)
  end

  def administrator_ids
    administrators.map(&:id)
  end

  def administrator_ids=(ids)
    create_admin_role.user_ids = ids
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include SectionResourceController

  def shift_totals
    @start_date = params[:start_date] ? Date.parse(params[:start_date]) : Date.today.at_beginning_of_month
    @end_date = params[:end_date] ? Date.parse(params[:end_date]) : Date.today
    @shifts = @section.active_shifts(:as_of => @start_date)
    @shift_tags = @section.shift_tags
    @physicians_by_group = @section.members_by_group
    dates = (@start_date..@end_date).to_a
    published_schedules = @section.weekly_schedules.published.include_dates(dates)
    published_dates = published_schedules.map(&:dates).flatten
    published_search_dates = published_dates & dates
    physician_ids = @physicians_by_group.values.flatten.map(&:id)
    assignments = @section.assignments.
      where(:physician_id => physician_ids, :date => published_search_dates)
    @totals_by_physician_and_shift = assignments.
      each_with_object({}) do |assignment, hsh|
        key = [assignment.physician_id, assignment.shift_id]
        hsh[key] = (hsh[key] ||= 0.0) + assignment.fixed_duration
      end
    @totals_by_group_and_shift = {}
    @totals_by_physician_and_tag = {}
    @totals_by_physician_and_shift.each do |key, total|
      physician_id, shift_id = key
      @physicians_by_group.each do |group_name, physicians|
        if physicians.map(&:id).include?(physician_id)
          key = [group_name, shift_id]
          @totals_by_group_and_shift[key] ||= 0.0
          @totals_by_group_and_shift[key] += total
        end
      end
      @shift_tags.each do |tag|
        if tag.shift_ids.include?(shift_id)
          key = [physician_id, tag.id]
          @totals_by_physician_and_tag[key] ||= 0.0
          @totals_by_physician_and_tag[key] += total
        end
      end
    end
    @totals_by_group_and_tag = {}
    @totals_by_physician_and_tag.each do |key, total|
      physician_id, tag_id = key
      @physicians_by_group.each do |group_name, physicians|
        if physicians.map(&:id).include?(physician_id)
          key = [group_name, tag_id]
          @totals_by_group_and_tag[key] ||= 0.0
          @totals_by_group_and_tag[key] += total
        end
      end
    end

    respond_to do |format|
      format.html
      format.xls { render :xls => @section, :layout => false,
        :template => "reports/section_report.xls" }
    end
  end

  def search_shift_totals
    @shift_totals_report = ::Logical::ShiftTotalsReport.new
  end

  def shift_totals_report
    @shift_totals_report = ::Logical::ShiftTotalsReport.
      new(params[:logical_shift_totals_report])
    @shift_totals_report.section = @section

    unless @shift_totals_report.valid?
      flash.now[:error] = "Unable to generate report: #{@shift_totals_report.errors.full_messages.join(", ")}"
      return(render :search_shift_totals)
    end

    respond_to do |format|
      format.html
      format.xls { render :xls => @shift_totals_report, :layout => false }
    end
  end

  def shift_totals_by_day
    @shift_totals_report = ::Logical::ShiftTotalsReport.
      new(params[:logical_shift_totals_report])
    @shift_totals_report.section = @section
    @shift = Shift.find(params[:shift_id])
  end

  def section_physician_shift_totals
    find_physician
    @start_date = params[:start_date] ? Date.parse(params[:start_date]) : Date.today.at_beginning_of_month
    @end_date = params[:end_date] ? Date.parse(params[:end_date]) : Date.today
    dates = (@start_date..@end_date).to_a
    published_schedules = @section.weekly_schedules.published.include_dates(dates)
    published_dates = published_schedules.map(&:dates).flatten
    assignments = @section.assignments.
      where(:physician_id => @physician.id, :date => published_dates)
    @shifts = Shift.find(assignments.map(&:shift_id).uniq)
    @assignment_by_shift_and_date = assignments.each_with_object({}) do |assignment, hsh|
      hsh[[assignment.shift, assignment.date]] = assignment
    end
  end

  private

  def find_physician
    physician_id = params[:physician_id]
    return(redirect_to(section_shift_totals_path(@section))) unless physician_id
    @physician = @section.members.find(physician_id)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper

  def physician_groups
    @physician_groups ||= RadDirectory::Group.find_all_by_title(Section::SCHEDULE_GROUPS)
  end
end

app/views/reports/search_shift_totals.html.haml
- page_title "Search #{@section.title} reports"

- content_for :javascripts do
  = javascript_include_tag "shared/checkboxes"
  = javascript_include_tag "shared/date_span_selector"
  :javascript
    $(function() {
      $("#logical_shift_totals_report_start_date").
        date_span_selector("logical_shift_totals_report_end_date");
    });

%h3 Report on Shift Totals for Published Schedules

= semantic_form_for @shift_totals_report, :url => shift_totals_report_section_reports_path(@section) do |report_form|
  = report_form.inputs "Date Range" do
    = report_form.input :start_date, :label => "From"
    = report_form.input :end_date, :label => "To"

  %fieldset.inputs
    %legend Shifts
    %div{ :style => "margin-left: 25%;" }
      = check_box_tag "logical_shift_totals_report[hide_empty_shifts]", 1, true
      = label_tag "logical_shift_totals_report[hide_empty_shifts]", "Hide unpopulated shifts?"
      %br
      %br
      = link_to "select all", "#", :class => "check_all_boxes"
      |
      = link_to "select none", "#", :class => "uncheck_all_boxes"
      %br
      %br
      - per_column = 15
      - section_shifts = @section.active_shifts
      - 0.step(section_shifts.count, per_column) do |index|
        %div{ :style => "float: left;" }
          - (section_shifts[index, per_column]).each do |shift|
            = check_box_tag "logical_shift_totals_report[shift_ids][]", shift.id, @shift_totals_report.shift_ids.nil? || @shift_totals_report.shift_ids.include?(shift.id)
            = label_tag "logical_shift_totals_report[shift_ids][]", shift.title
            %br

  %fieldset.inputs
    %legend Groups
    %div{ :style => "margin-left: 25%;" }
      - %w( Faculty Fellows Residents ).each do |group|
        = check_box_tag "logical_shift_totals_report[groups][]", group, @shift_totals_report.groups.nil? || @shift_totals_report.groups.include?(group)
        = label_tag "logical_shift_totals_report[groups][]", group
        %br

  = report_form.buttons do
    = report_form.commit_button "Generate Report", :button_html => { :class => "button" }

app/views/reports/section_physician_shift_totals.haml
- content_for :javascripts do
  = javascript_include_tag 'shared/date_selector'

- content_for :stylesheets do
  = stylesheet_link_tag 'reports'

- content_for :content_menu do
  = render "schedules/section_menu"

%h3= "Totals from Published Schedules for #{@physician.full_name}"

%div.subheadline
  = form_tag section_physician_shift_totals_path(@section, @physician), :method => :get do
    %h3
      %span#start_date_text= @start_date.to_s(:long)
    %div.inline_form
      = text_field_tag "start_date", @start_date.to_s
    %h3
      %span to&nbsp;
      %span#end_date_text= @end_date.to_s(:long)
    %div.inline_form
      = text_field_tag "end_date", @end_date.to_s

%table.decimal_data
  %thead
    %tr
      %th
      - (@start_date..@end_date).each do |date|
        %th= short_date(date)
    - @shifts.each do |shift|
      %tr
        %th= "#{shift.title} (#{shift.duration})"
        - (@start_date..@end_date).each do |date|
          - if @assignment_by_shift_and_date[[shift, date]]
            %td= @assignment_by_shift_and_date[[shift, date]].fixed_duration
          -else
            %td &nbsp;

app/views/reports/section_physician_shift_totals.html.haml
- content_for :javascripts do
  = javascript_include_tag 'shared/date_selector'

- content_for :stylesheets do
  = stylesheet_link_tag 'reports'

%h3= "Totals from Published Schedules for #{@physician.full_name}"

%div.subheadline
  = form_tag section_physician_shift_totals_path(@section, @physician), :method => :get do
    %h3
      %span#start_date_text= @start_date.to_s(:long)
    %div.inline_form
      = text_field_tag "start_date", @start_date.to_s
    %h3
      %span to&nbsp;
      %span#end_date_text= @end_date.to_s(:long)
    %div.inline_form
      = text_field_tag "end_date", @end_date.to_s

%table.decimal_data
  %thead
    %tr
      %th
      - (@start_date..@end_date).each do |date|
        %th= date.to_s(:short_with_weekday)
    - @shifts.each do |shift|
      %tr
        %th= "#{shift.title} (#{shift.duration})"
        - (@start_date..@end_date).each do |date|
          - if @assignment_by_shift_and_date[[shift, date]]
            %td= @assignment_by_shift_and_date[[shift, date]].fixed_duration
          -else
            %td &nbsp;

app/views/reports/shift_totals.html.haml
- page_title "#{@section.title} reports"

- content_for :javascripts do
  = javascript_include_tag 'shared/date_selector'
  = javascript_include_tag 'report'

%h3 Totals from Published Weekly Schedules

%p= link_to "Reports Search", search_shift_totals_section_reports_path(@section)

%div.subheadline
  = semantic_form_for @section, :url => section_shift_totals_path(@section), :html => { :method => :get } do |report_form|
    %h3
      %span#start_date_text= @start_date.to_s(:long)
    %div.inline_form
      = text_field_tag "start_date", @start_date.to_s
    %h3
      %span to&nbsp;
      %span#end_date_text= @end_date.to_s(:long)
    %div.inline_form
      = text_field_tag "end_date", @end_date.to_s
    %ol
      = report_form.commit_button "Get Report", :button_html => { :class => "button" }

%p= link_to 'Download as Excel', section_shift_totals_path(@section, :format => :xls, :start_date => @start_date, :end_date => @end_date), { :class => "button" }

%table.decimal_data
  %thead
    %tr{ :class => cycle("odd", "", :name => "row") }
      %th
      - @physicians_by_group.each do |group_name, people|
        - unless people.blank?
          %th{ :class => "group" }
            %span{ :class => "title" }= group_name
          = render :partial => "reports/headers/physician", :collection => people, :locals => { :section => @section, :group_name => group_name, :start_date => @start_date, :end_date => @end_date }
  %tfoot
    %tr
      %th
      - @physicians_by_group.each do |group_name, people|
        - unless people.blank?
          %th{ :class => "group" }
            %span{ :class => "title" }= group_name
          = render :partial => "reports/headers/physician", :collection => people, :locals => { :section => @section, :group_name => group_name, :start_date => @start_date, :end_date => @end_date }
  %tbody
    - @shifts.each do |shift|
      %tr{ :class => cycle("odd", "", :name => "row") }
        %th.shift_label.odd= "#{shift.title} (#{shift.duration})"
        - @physicians_by_group.each do |group_name, people|
          - unless people.blank?
            %td.total= @totals_by_group_and_shift[[group_name, shift.id]]
            - people.each do |person|
              %td{ :class => cycle("odd #{group_name}", group_name, :name => "col") }><= @totals_by_physician_and_shift[[person.id, shift.id]]

%br

%table.decimal_data
  %thead
    %tr{ :class => cycle("odd", "", :name => "row") }
      %th Shift Categories
      - @physicians_by_group.each do |group_name, people|
        %th{ :class => "group" }
          %span{ :class => "title" }= group_name
        = render :partial => "reports/headers/physician", :collection => people, :locals => { :section => @section, :group_name => group_name, :start_date => @start_date, :end_date => @end_date }
  %tbody
    - @shift_tags.each do |shift_tag|
      %tr{ :class => cycle("odd", "", :name => "row") }
        %th{ :class => cycle("odd", "", :name => "col") }= shift_tag.title
        - @physicians_by_group.each do |group_name, physician|
          %td.total= @totals_by_group_and_tag[[group_name, shift_tag.id]]
          - physician.each do |physician|
            %td{ :class => cycle("odd #{group_name}", group_name, :name => "col") }><= @totals_by_physician_and_tag[[physician.id, shift_tag.id]]

app/views/reports/shift_totals_by_day.html.haml
%h3= "Daily Totals for #{@shift.title}, #{@shift_totals_report.start_date.strftime("#{@shift_totals_report.start_date.day} %B %Y")} - #{@shift_totals_report.end_date.strftime("#{@shift_totals_report.end_date.day} %B %Y")}"

%table
  %thead
    %tr
      %th
      - @shift_totals_report.physicians_by_group.each do |group, physicians|
        %th= group
        = render :partial => "/reports/headers/physician", :collection => physicians, :locals => { :section => @section, :group_name => nil, :start_date => @start_date, :end_date => @end_date }
  %tbody
    - totals_by_physician_id_and_day = @shift_totals_report.totals_by_physician_id_and_day(@shift.id)
    - totals_by_group_and_day = @shift_totals_report.totals_by_group_and_day(@shift.id)
    - {1=>"Monday", 2=>"Tuesday", 3=>"Wednesday", 4=>"Thursday", 5=>"Friday", 6=>"Saturday", 0=>"Sunday"}.each do |day, day_name|
      %tr{ :class => cycle("odd", "", :name => "row") }
        %th= day_name
        - @shift_totals_report.physicians_by_group.each do |group, physicians|
          %td= totals_by_group_and_day[[group, day]]
          - physicians.each do |physician|
            %td= totals_by_physician_id_and_day[[physician.id, day]]

app/views/reports/shift_totals_report.html.haml
- page_title "Report for #{@section.title}"

%h3= "Report for #{@shift_totals_report.start_date.strftime("#{@shift_totals_report.start_date.day} %B %Y")} - #{@shift_totals_report.end_date.strftime("#{@shift_totals_report.end_date.day} %B %Y")}"

%p= link_to "Generate another report", search_shift_totals_section_reports_path(@section)

= semantic_form_for @shift_totals_report, :url => shift_totals_report_section_reports_path(@section, :format => :xls) do |report_form|
  = report_form.input :start_date, :as => :hidden, :wrapper_html => { :style => "display: none;" }
  = report_form.input :end_date, :as => :hidden, :wrapper_html => { :style => "display: none;" }
  = report_form.input :hide_empty_shifts, :as => :hidden, :wrapper_html => { :style => "display: none;" }
  = report_form.input :shift_ids, :as => :hidden, :wrapper_html => { :style => "display: none;" }
  - @shift_totals_report.groups.each do |group|
    = hidden_field_tag "logical_shift_totals_report[groups][]", group
  = report_form.commit_button :label => "Download Excel"

%p Select a shift below to view totals by day of the week.

%div.fixed-table-wrapper
  %table
    %thead
      %tr
        %th
        - @shift_totals_report.physicians_by_group.each do |group, physicians|
          %th= group
          = render :partial => "/reports/headers/physician", :collection => physicians, :locals => { :section => @section, :group_name => nil, :start_date => @start_date, :end_date => @end_date }
    %tbody
      - @shift_totals_report.shifts.each do |shift|
        %tr{ :class => cycle("odd", "", :name => "row") }
          %th= link_to shift.title, totals_by_day_section_reports_path(@section, shift, :logical_shift_totals_report => params[:logical_shift_totals_report])
          - @shift_totals_report.physicians_by_group.each do |group, physicians|
            %td= @shift_totals_report.totals_by_group_and_shift_id[[group, shift.id]]
            - physicians.each do |physician|
              %td><= @shift_totals_report.totals_by_physician_id_and_shift_id[[physician.id, shift.id]]